### ISSUE TITLE
how to process the array vs just printing to command: "get_live_interval_bars" 

### ISSUE THREAD

**Issue by emilge** [akapur/pyiqfeed#47]
I have the same issue, which was previously raised, but no resolution posted. Any ideas on that ? 

"cannot seem to override the `def process_history_bar(self, bar_data: np.array)` inside of `def get_live_interval_bars` to actually process the array vs just printing to command.  the above snippet works fine to simply output to command and I know that I need to override the function process_history_bar or process_live_bar to manipulate in real-time but can not seem to be able to do so.  Could you update the small snippet to show how you are overriding the process function?  Also, did you get access to IQ feed?"

_Originally posted by @blonc in https://github.com/akapur/pyiqfeed/issues/46#issuecomment-620255262_

**Comment by akapur** [comment]
My response to the previous issue raised was that I did not understand what
the issue was and it seems blonc figured this out.

If the question is what I understand it to be, it seems to me, you could
resolve your issue by:

a) Reading up on Python, particularly how classes work and how to override
functions in classes.
b) Read the Readme file in the repository and the copious documentation for
each class and function.
c) Call the IQFeed sales or support numbers. They are a commercial
organization where people actually get paid to give you access to IQFeed in
return for money. In contrast to them I'm letting you have access to
something I found useful for no money. Once you have access to IQFeed, read
the IQFeed documentation. I have no connection to DTN, the company who
provides IQFeed, not even a discounted feed.

Once you have done the above, if you have a specific problem with the
library as opposed to Python in general or IQFeed, please open an issue and
if it's a bug or some such, I'd be happy to help.

**Comment by akapur** [comment]
Not a pyiqfeed issue.
